[package]
name = "cratesio"
version = "0.1.0"
authors = ["panicbit <panicbit.dev@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.3"
url = "1.7.1"
serde = "1.0.80"
serde_derive = "1.0.80"
futures = "0.1.25"
